---
title: "Week 3: GGPLOT & Addressing Margins of Error"
description: "Using ggplot for data visualization and addressing margins of error in data"
date: 2026-09-11
---

## What We Did

Went over the basic elements and syntax of using ggplot for data visualization. Discussed how to properly address margins of error in ACS data.

## Key Concepts

Visualizing data is important because different datasets can have similar (or even identical) summary statistics but look very different (i.e. Ansombe's Quartet).

- A plot is a mapping from columns in a dataset to visual properties on a page. Known as "Grammer of Graphics" ("GG").
- Ex: estimate column -> position on y-axis, population column -> postition on x-axis


GGPLOT Basics
plot1 <- ggplot(data) +    this creates a blank canvas with your data as reference
  aes() +                  despite the name, "aesthetics" refers to column assignment
  geom_something()         shape/type of chart
      
"Decorations" (i.e. colors, etc.) go in geom_*() portion of code, not aes()

Options for geom:

- histogram
- point (for scatterplot)
- boxplot
- col (for barchart)
- line
- errorbar

Combining 2 geom:

- Each type has its own aes specfications
- Ex: geom_col() has aes( x = somevalue, y = somevalue), while geom_errorbar() has aes(ymin = somevalue, ymax = somevalue)

Extra:

- facet_wrap() for creating multiple charts side-by-side for comparison
- coord_flip() to flip x and y axis orientation
- mutate(str_remove(column, "__")) to remove some text/edit a column
- Can use theme_minimal() for graphs as a shortcut for nice aesthetics
- labs() for the labels of a graph



Census Bureau uses coefficient of variation ("CV").

- CV is a relative measure of sampling error, tied to the 90% confidence interval.
- Census assumes a low CV of 15% (high reliability), medium of 15-30%, and high > 30% (low reliability, high sampling error)


Derived uncertainty

- Cannot simply add up or multiply margins of error when comparing different estimates
- In tidycensus: moe_sum() will properly add moe's for different estimates
  - Also: moe_prop() for one estimate as a share of another, and moe_ratio() for ratio of 2 variables


Change over time with ACS data

- 5-year ACS estimates have overlapping time periods when comparing years that are close together (ex: 2023 and 2022)
- Instead, use ACS years that do not have overlapping periods (ex: 2018 and 2023)
- Standard error of difference and confidence interval of change to determine if the difference in estimates between years is real (i.e. does not include zero)


